version: '2'

services:
services:
    haproxy:
      build: ./haproxy
      image: haproxy-redis
      depends_on:
         - redis_master
         - redis_slave
      ports:
        - "6379:6379"
        - "6380:6380"
   
    redis_master:
        image: redis:3.2.11-alpine
        ports:
          - "16379:6379"

    redis_slave:
        image: redis:3.2.11-alpine
        ports:
          - "16380:6379"
      
    sentinel:
        build: ./redis-sentinel
        image: redis-sentinel
        environment:
            - MASTER_NAME=mymaster
            - QUORUM=1
            - MASTER=redis_master
            - SLAVES=redis_slave
        depends_on:
            - redis_master